FROM alpine:latest as base
RUN apk --no-cache --update upgrade && apk --no-cache add ca-certificates

#FROM scratch
#COPY --from=base /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

RUN apk update \
	&& apk upgrade \
	&& apk add bash git yarn docker

#COPY dist /

VOLUME /i3c

WORKDIR /

#ENTRYPOINT ["/portainer"]
   
	
#EXPOSE 9000
COPY run-i3c.sh /
RUN chmod a+x /run-i3c.sh
COPY run-loop.sh /
RUN chmod a+x /run-loop.sh
CMD ["/run-loop.sh"]

