# To Deploy i3c demo (demo.i3c.cloud) in a play-with-docker playground
#
# - Go to:
# http://play-with-docker.com/?stack=https://raw.githubusercontent.com/virtimus/i3c/develop/i3c-install/stack5.yml
# - Login and/or Start.
# - Wait until 'Your session is ready!' and 'Close' modal.
# - Refresh (if a shell is not shown).
# - Wait until a link with text '80' is shown. It is the link to the demo.
# In case of problems check bootstrap logs:
# - /var/log/bootstrap.log - log from install/build
# - /log/grunt-run-dev.log - log from run-dev (i3c container startup)
# - Visit https://github.com/virtimus/i3c to check default credentials (admin/i3cadmin)
# 
# reference: https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/
# 
version: '3'
services:
  trigger:
    image: franela/dind
    command: sh -c "cd / && git clone https://github.com/virtimus/i3c.git && ./i3c/i3c-install/bootstrap.sh >> /log/bootstrap.log && tail -f /dev/null"
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock','/var/log:/log' ]
